server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_ms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ziyad1917
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: "loans"